# Sample config yaml
strategy: "RoundRobin"
services: 
  - name: "Service01"
    matcher: "/api/v1"
    strategy: "RoundRobin"
    replicas: 
    - url: "http://localhost:8081"
    - url: "http://localhost:8082"